USE [master]
GO

/****** Object:  Database [ODeskJobsSearch]    Script Date: 07/13/2014 11:57:51 ******/
CREATE DATABASE [ODeskJobsSearch] ON  PRIMARY 
( NAME = N'ODeskJobsSearch', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ODeskJobsSearch.mdf' , SIZE = 13312KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ODeskJobsSearch_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ODeskJobsSearch_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ODeskJobsSearch] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ODeskJobsSearch].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ODeskJobsSearch] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET ARITHABORT OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ODeskJobsSearch] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ODeskJobsSearch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ODeskJobsSearch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ODeskJobsSearch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ODeskJobsSearch] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ODeskJobsSearch] SET  READ_WRITE 
GO

ALTER DATABASE [ODeskJobsSearch] SET RECOVERY FULL 
GO

ALTER DATABASE [ODeskJobsSearch] SET  MULTI_USER 
GO

ALTER DATABASE [ODeskJobsSearch] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ODeskJobsSearch] SET DB_CHAINING OFF 
GO


